// source: ActionMessage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.gw_messages.ActionMessage');
goog.provide('proto.gw_messages.ActionMessage.ActionType');
goog.provide('proto.gw_messages.ActionMessage.ActionsOneofCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.gw_messages.AttackTarget');
goog.require('proto.gw_messages.AttackTargetByAgentId');
goog.require('proto.gw_messages.ChangeTargetToAgentId');
goog.require('proto.gw_messages.MoveToPosition');
goog.require('proto.gw_messages.UseSkillById');
goog.require('proto.gw_messages.UseSkillSlot');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gw_messages.ActionMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.gw_messages.ActionMessage.oneofGroups_);
};
goog.inherits(proto.gw_messages.ActionMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gw_messages.ActionMessage.displayName = 'proto.gw_messages.ActionMessage';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.gw_messages.ActionMessage.oneofGroups_ = [[2,3,4,5,6,7]];

/**
 * @enum {number}
 */
proto.gw_messages.ActionMessage.ActionsOneofCase = {
  ACTIONS_ONEOF_NOT_SET: 0,
  ATTACK_TARGET: 2,
  ATTACK_TARGET_BY_AGENT_ID: 3,
  CHANGE_TARGET_TO_AGENT_ID: 4,
  MOVE_TO_POSITION: 5,
  USE_SKILL_BY_ID: 6,
  USE_SKILL_SLOT: 7
};

/**
 * @return {proto.gw_messages.ActionMessage.ActionsOneofCase}
 */
proto.gw_messages.ActionMessage.prototype.getActionsOneofCase = function() {
  return /** @type {proto.gw_messages.ActionMessage.ActionsOneofCase} */(jspb.Message.computeOneofCase(this, proto.gw_messages.ActionMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gw_messages.ActionMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.gw_messages.ActionMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gw_messages.ActionMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gw_messages.ActionMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    actionType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    attackTarget: (f = msg.getAttackTarget()) && proto.gw_messages.AttackTarget.toObject(includeInstance, f),
    attackTargetByAgentId: (f = msg.getAttackTargetByAgentId()) && proto.gw_messages.AttackTargetByAgentId.toObject(includeInstance, f),
    changeTargetToAgentId: (f = msg.getChangeTargetToAgentId()) && proto.gw_messages.ChangeTargetToAgentId.toObject(includeInstance, f),
    moveToPosition: (f = msg.getMoveToPosition()) && proto.gw_messages.MoveToPosition.toObject(includeInstance, f),
    useSkillById: (f = msg.getUseSkillById()) && proto.gw_messages.UseSkillById.toObject(includeInstance, f),
    useSkillSlot: (f = msg.getUseSkillSlot()) && proto.gw_messages.UseSkillSlot.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gw_messages.ActionMessage}
 */
proto.gw_messages.ActionMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gw_messages.ActionMessage;
  return proto.gw_messages.ActionMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gw_messages.ActionMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gw_messages.ActionMessage}
 */
proto.gw_messages.ActionMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.gw_messages.ActionMessage.ActionType} */ (reader.readEnum());
      msg.setActionType(value);
      break;
    case 2:
      var value = new proto.gw_messages.AttackTarget;
      reader.readMessage(value,proto.gw_messages.AttackTarget.deserializeBinaryFromReader);
      msg.setAttackTarget(value);
      break;
    case 3:
      var value = new proto.gw_messages.AttackTargetByAgentId;
      reader.readMessage(value,proto.gw_messages.AttackTargetByAgentId.deserializeBinaryFromReader);
      msg.setAttackTargetByAgentId(value);
      break;
    case 4:
      var value = new proto.gw_messages.ChangeTargetToAgentId;
      reader.readMessage(value,proto.gw_messages.ChangeTargetToAgentId.deserializeBinaryFromReader);
      msg.setChangeTargetToAgentId(value);
      break;
    case 5:
      var value = new proto.gw_messages.MoveToPosition;
      reader.readMessage(value,proto.gw_messages.MoveToPosition.deserializeBinaryFromReader);
      msg.setMoveToPosition(value);
      break;
    case 6:
      var value = new proto.gw_messages.UseSkillById;
      reader.readMessage(value,proto.gw_messages.UseSkillById.deserializeBinaryFromReader);
      msg.setUseSkillById(value);
      break;
    case 7:
      var value = new proto.gw_messages.UseSkillSlot;
      reader.readMessage(value,proto.gw_messages.UseSkillSlot.deserializeBinaryFromReader);
      msg.setUseSkillSlot(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gw_messages.ActionMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gw_messages.ActionMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gw_messages.ActionMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gw_messages.ActionMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.gw_messages.ActionMessage.ActionType} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAttackTarget();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.gw_messages.AttackTarget.serializeBinaryToWriter
    );
  }
  f = message.getAttackTargetByAgentId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.gw_messages.AttackTargetByAgentId.serializeBinaryToWriter
    );
  }
  f = message.getChangeTargetToAgentId();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.gw_messages.ChangeTargetToAgentId.serializeBinaryToWriter
    );
  }
  f = message.getMoveToPosition();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.gw_messages.MoveToPosition.serializeBinaryToWriter
    );
  }
  f = message.getUseSkillById();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.gw_messages.UseSkillById.serializeBinaryToWriter
    );
  }
  f = message.getUseSkillSlot();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.gw_messages.UseSkillSlot.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.gw_messages.ActionMessage.ActionType = {
  NONE: 0,
  ATTACKTARGET: 1,
  ATTACKTARGETBYAGENTID: 2,
  USESKILLSLOT: 3,
  USESKILLBYID: 4,
  CHANGETARGETTOAGENTID: 5,
  MOVETOPOSITION: 6
};

/**
 * optional ActionType action_type = 1;
 * @return {!proto.gw_messages.ActionMessage.ActionType}
 */
proto.gw_messages.ActionMessage.prototype.getActionType = function() {
  return /** @type {!proto.gw_messages.ActionMessage.ActionType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.gw_messages.ActionMessage.ActionType} value
 * @return {!proto.gw_messages.ActionMessage} returns this
 */
proto.gw_messages.ActionMessage.prototype.setActionType = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.gw_messages.ActionMessage} returns this
 */
proto.gw_messages.ActionMessage.prototype.clearActionType = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gw_messages.ActionMessage.prototype.hasActionType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional AttackTarget attack_target = 2;
 * @return {?proto.gw_messages.AttackTarget}
 */
proto.gw_messages.ActionMessage.prototype.getAttackTarget = function() {
  return /** @type{?proto.gw_messages.AttackTarget} */ (
    jspb.Message.getWrapperField(this, proto.gw_messages.AttackTarget, 2));
};


/**
 * @param {?proto.gw_messages.AttackTarget|undefined} value
 * @return {!proto.gw_messages.ActionMessage} returns this
*/
proto.gw_messages.ActionMessage.prototype.setAttackTarget = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.gw_messages.ActionMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gw_messages.ActionMessage} returns this
 */
proto.gw_messages.ActionMessage.prototype.clearAttackTarget = function() {
  return this.setAttackTarget(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gw_messages.ActionMessage.prototype.hasAttackTarget = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional AttackTargetByAgentId attack_target_by_agent_id = 3;
 * @return {?proto.gw_messages.AttackTargetByAgentId}
 */
proto.gw_messages.ActionMessage.prototype.getAttackTargetByAgentId = function() {
  return /** @type{?proto.gw_messages.AttackTargetByAgentId} */ (
    jspb.Message.getWrapperField(this, proto.gw_messages.AttackTargetByAgentId, 3));
};


/**
 * @param {?proto.gw_messages.AttackTargetByAgentId|undefined} value
 * @return {!proto.gw_messages.ActionMessage} returns this
*/
proto.gw_messages.ActionMessage.prototype.setAttackTargetByAgentId = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.gw_messages.ActionMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gw_messages.ActionMessage} returns this
 */
proto.gw_messages.ActionMessage.prototype.clearAttackTargetByAgentId = function() {
  return this.setAttackTargetByAgentId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gw_messages.ActionMessage.prototype.hasAttackTargetByAgentId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ChangeTargetToAgentId change_target_to_agent_id = 4;
 * @return {?proto.gw_messages.ChangeTargetToAgentId}
 */
proto.gw_messages.ActionMessage.prototype.getChangeTargetToAgentId = function() {
  return /** @type{?proto.gw_messages.ChangeTargetToAgentId} */ (
    jspb.Message.getWrapperField(this, proto.gw_messages.ChangeTargetToAgentId, 4));
};


/**
 * @param {?proto.gw_messages.ChangeTargetToAgentId|undefined} value
 * @return {!proto.gw_messages.ActionMessage} returns this
*/
proto.gw_messages.ActionMessage.prototype.setChangeTargetToAgentId = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.gw_messages.ActionMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gw_messages.ActionMessage} returns this
 */
proto.gw_messages.ActionMessage.prototype.clearChangeTargetToAgentId = function() {
  return this.setChangeTargetToAgentId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gw_messages.ActionMessage.prototype.hasChangeTargetToAgentId = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional MoveToPosition move_to_position = 5;
 * @return {?proto.gw_messages.MoveToPosition}
 */
proto.gw_messages.ActionMessage.prototype.getMoveToPosition = function() {
  return /** @type{?proto.gw_messages.MoveToPosition} */ (
    jspb.Message.getWrapperField(this, proto.gw_messages.MoveToPosition, 5));
};


/**
 * @param {?proto.gw_messages.MoveToPosition|undefined} value
 * @return {!proto.gw_messages.ActionMessage} returns this
*/
proto.gw_messages.ActionMessage.prototype.setMoveToPosition = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.gw_messages.ActionMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gw_messages.ActionMessage} returns this
 */
proto.gw_messages.ActionMessage.prototype.clearMoveToPosition = function() {
  return this.setMoveToPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gw_messages.ActionMessage.prototype.hasMoveToPosition = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional UseSkillById use_skill_by_id = 6;
 * @return {?proto.gw_messages.UseSkillById}
 */
proto.gw_messages.ActionMessage.prototype.getUseSkillById = function() {
  return /** @type{?proto.gw_messages.UseSkillById} */ (
    jspb.Message.getWrapperField(this, proto.gw_messages.UseSkillById, 6));
};


/**
 * @param {?proto.gw_messages.UseSkillById|undefined} value
 * @return {!proto.gw_messages.ActionMessage} returns this
*/
proto.gw_messages.ActionMessage.prototype.setUseSkillById = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.gw_messages.ActionMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gw_messages.ActionMessage} returns this
 */
proto.gw_messages.ActionMessage.prototype.clearUseSkillById = function() {
  return this.setUseSkillById(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gw_messages.ActionMessage.prototype.hasUseSkillById = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional UseSkillSlot use_skill_slot = 7;
 * @return {?proto.gw_messages.UseSkillSlot}
 */
proto.gw_messages.ActionMessage.prototype.getUseSkillSlot = function() {
  return /** @type{?proto.gw_messages.UseSkillSlot} */ (
    jspb.Message.getWrapperField(this, proto.gw_messages.UseSkillSlot, 7));
};


/**
 * @param {?proto.gw_messages.UseSkillSlot|undefined} value
 * @return {!proto.gw_messages.ActionMessage} returns this
*/
proto.gw_messages.ActionMessage.prototype.setUseSkillSlot = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.gw_messages.ActionMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gw_messages.ActionMessage} returns this
 */
proto.gw_messages.ActionMessage.prototype.clearUseSkillSlot = function() {
  return this.setUseSkillSlot(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gw_messages.ActionMessage.prototype.hasUseSkillSlot = function() {
  return jspb.Message.getField(this, 7) != null;
};


